resolver: lts-15.9

packages:
- '.'

extra-deps:
- aeson-1.4.5.0
- extensible-effects-5.0.0.1
- fused-effects-1.0.0.1
- polysemy-1.3.0.0
- polysemy-plugin-0.2.5.0

flags: {}
extra-package-dbs: []

ghc-options:
  "$locals": -fhide-source-paths
