resolver: lts-14.16

packages:
- '.'

extra-deps:
- aeson-1.4.5.0
- extensible-effects-5.0.0.1
- polysemy-1.2.3.0
- polysemy-plugin-0.2.4.0

flags: {}
extra-package-dbs: []

ghc-options:
  "$locals": -fhide-source-paths
